kind: pipeline
type: docker
name: pipeline-test

trigger:
  event:
    - push

steps:
- name: greeting
  image: alpine
  environment:
    DB_NAME:
      from_secret: db_name
  commands:
  - echo $DB_NAME

  ---
  kind: secret
  name: db_name
  get:
    path: kv-v2/eucalypto
    name: db_name