kind: pipeline
type: docker
name: "Test Development Push"

trigger:
  branch:
    - dev/*
  event:
    include:
      - push

steps:
- name: Run test on latest changes
  image: pfeiffermax/python-poetry:1.11.0-poetry1.8.3-python3.12.3-bookworm
  commands:
  - poetry install --with test
  - poetry run pytest
  
---
kind: pipeline
type: docker
name: 'Test Dev Server Stage'

trigger:
  branch:
    - staging
  event:
    - push


steps:
- name: Run tests and build
  image: pfeiffermax/python-poetry:1.11.0-poetry1.8.3-python3.12.3-bookworm
  commands:
    - poetry install --with test
    - poetry run pytest
    - poetry build
    - poetry version patch
    - TAG_VALUE=$(poetry version | cut -d' ' -f2-) 
    - apt install git -y
    - git tag $TAG_VALUE
    - mkdir ../eucalypto-${TAG_VALUE}
    - ls ..

- name: Pack build
  image: chainguard/git
  commands:
    - echo ${DRONE_SEMVER}


- name: 'Sync to staging server'
  image: appleboy/drone-scp
  settings:
    host: 
      from_secret: dev-server
    username: 
      from_secret: dev-server-user 
    key: 
      from_secret: dev-server-key
    target: ${PATH_BUILD_DIR}
    source: ./*
    overwrite: true
  environment:
    DEV_SERVER_PATH:
      from_secret: dev-server-path
    PATH_BUILD_DIR:
      ${DEV_SERVER_PATH}${DRONE_SEMVER}

- name: 'Commit version update'
  image: chainguard/git
  commands:
    - git status

- name: 'Start server'
  image: debian
  commands:
    - echo Start a script on the web server to update the build
  
---
kind: pipeline
type: docker
name: 'Main branch test'

trigger:
  branch:
    - main
  event:
    - push

steps:
- name: 'Run Tests'
  image: pfeiffermax/python-poetry:1.11.0-poetry1.8.3-python3.12.3-bookworm
  commands:
  - poetry install
  - poetry run pytest

---
kind: secret
name: dev-server
get:
  path: kv-v2/data/eucalypto/dev-stage
  name: server-address

---
kind: secret
name: dev-server-path
get:
  path: kv-v2/data/eucalypto/dev-stage
  name: target-path

---
kind: secret
name: dev-server-user
get:
  path: kv-v2/data/eucalypto/dev-stage
  name: dev-server-user

---
kind: secret
name: dev-server-key
get:
  path: kv-v2/data/eucalypto/dev-stage
  name: dev-server-key

---
kind: secret
name: db_name
get:
  path: kv-v2/data/eucalypto/db-info
  name: db_name

---
kind: secret
name: username
get:
  path: kv-v2/data/eucalypto/db-info
  name: db_username

--- 
kind: secret
name: password
get:
  path: kv-v2/data/eucalypto/db-info
  name: db_password