kind: pipeline
type: docker
name: "Test Environment"

trigger:
  branch:
    - dev
  event:
    include:
      - push

steps:
- name: 
  image: debian:12.6
  commands:
  - 
  environment:
    DB_NAME:
      from_secret: db_name
    DB_USERNAME:
      from_secret: username
    DB_PASSWORD:
      from_secret: password
  

---
kind: secret
name: db_name
get:
  path: kv-v2/data/eucalypto
  name: db_name

---
kind: secret
name: username
get:
  path: kv-v2/data/eucalypto
  name: username

--- kind: secret
name: password
get:
  path: kv-v2/data/eucalypto
  name: password