kind: pipeline
type: docker
name: "Test Development Push"

trigger:
  branch:
    - dev/*
  event:
    include:
      - push

steps:
- name: Run test on latest changes
  pull: always
  image: achawula/eucalypto-build:0.1
  commands:
  - poetry install --with test
  - poetry run pytest -rPf
  environment:
    ROLE_ID:
      from_secret: role-id
  
---
kind: pipeline
type: docker
name: 'Staging tests'

trigger:
  branch:
    - staging
  event:
    - push

steps:
- name: Run tests on staging
  image: achawula/eucalypto-build:0.1
  commands:
    - poetry install --with test
    - poetry run pytest -rPf
  environment:
    ROLE_ID:
      from_secret: role-id 

---
kind: pipeline
type: docker
name: Deploy to staging server

trigger:
  event:
  - promote
  target:
  - staging

steps:
- name: Version increment and repository update
  image: achawula/eucalypto-build:0.1
  commands:
    - poetry version patch
    - git add pyproject.toml
    - git commit -m "Increment eucalypto patch version"
    - git push gitea staging

- name: Create build directory for transfer
  image: achawula/eucalypto-build:0.1
  commands:
    - poetry build  
    - TAG_VALUE=$(poetry version | cut -d' ' -f2-) 
    - mkdir ./eucalypto-$TAG_VALUE

- name: Pack build
  image: achawula/eucalypto-build:0.1
  commands:
    - ls 
    - DEST_DIR=$(ls -d eucalypto-*)
    - rsync -Rr ./* ./$DEST_DIR
    - rm -rf ./$DEST_DIR/$DEST_DIR

- name: 'Sync to staging server'
  image: appleboy/drone-scp
  settings:
    host: 
      from_secret: dev-server
    username: 
      from_secret: dev-server-user 
    key: 
      from_secret: dev-server-key
    target: 
      from_secret: dev-server-path
    source: ./eucalypto-*/*
    overwrite: true

- name: 'Start server'
  image: achawula/eucalypto-build:0.1
  commands:
    - echo Start a script on the web server to update the build

---
kind: pipeline
type: docker
name: 'Main branch test'

trigger:
  branch:
    - main
  event:
    - push

steps:
- name: 'Run Tests'
  image: pfeiffermax/python-poetry:1.11.0-poetry1.8.3-python3.12.3-bookworm
  commands:
  - poetry install
  - poetry run pytest

---
kind: secret
name: dev-server
get:
  path: kv-v2/data/eucalypto/dev-stage
  name: server-address

---
kind: secret
name: dev-server-path
get:
  path: kv-v2/data/eucalypto/dev-stage
  name: target-path

---
kind: secret
name: dev-server-user
get:
  path: kv-v2/data/eucalypto/dev-stage
  name: dev-server-user

---
kind: secret
name: dev-server-key
get:
  path: kv-v2/data/eucalypto/dev-stage
  name: dev-server-key

---
kind: secret
name: db_name
get:
  path: kv-v2/data/eucalypto/db-info
  name: db_name

---
kind: secret
name: username
get:
  path: kv-v2/data/eucalypto/db-info
  name: db_username

--- 
kind: secret
name: password
get:
  path: kv-v2/data/eucalypto/db-info
  name: db_password

---
kind: secret
name: role-id
get:
  path: kv-v2/data/eucalypto/dev-stage
  name: role-id