kind: pipeline
type: docker
name: pipeline-test

trigger:
  event:
    - push

steps:
- name: set-env
  image: alpine
  commands:
  - echo ${DB_NAME}
  environment:
    DB_NAME:
      from_secret: db_name
  

---
kind: secret
name: db_name
get:
  path: /secret/eucalypto
  name: db_name