kind: pipeline
type: docker
name: "Test Environment"

trigger:
  branch:
    - dev
  event:
    include:
      - push

steps:
- name: Build Env
  image: pfeiffermax/python-poetry:1.11.0-poetry1.8.3-python3.12.3-bookworm
Mu
  commands:
  - poetry install
  - poetry build
  environment:
    DB_NAME:
      from_secret: db_name
    DB_USERNAME:
      from_secret: username
    DB_PASSWORD:
      from_secret: password
  
---
kind: pipeline
type: docker
name: "Server Test Stage"

trigger:
  branch:
    - main
  event:
    include:
      - push

steps:
- name: Build Env
  image: pfeiffermax/python-poetry:1.11.0-poetry1.8.3-python3.12.3-bookworm
Mu
  commands:
    - poetry install
    - poetry build
  environment:
    DB_NAME:
      from_secret: db_name
    DB_USERNAME:
      from_secret: username
    DB_PASSWORD:
      from_secret: password
  
---
kind: secret
name: db_name
get:
  path: kv-v2/data/eucalypto
  name: db_name

---
kind: secret
name: username
get:
  path: kv-v2/data/eucalypto
  name: username

--- 
kind: secret
name: password
get:
  path: kv-v2/data/eucalypto
  name: password