CREATE TYPE "HABIT_TYPE" AS ENUM (
  'ground cover',
  'herbaceous perennial',
  'small shrub',
  'medium shrub',
  'large shrub',
  'small tree',
  'medium tree',
  'large tree'
);

CREATE TYPE "MONTHS" AS ENUM (
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December'
);

CREATE TYPE "FLOWER_STAGE" AS ENUM (
  'New buds',
  'Pre-bloom',
  'Blooming/Opening',
  'Wilting',
  'Seeding'
);

CREATE TYPE "GENERIC_PLANT_ATTRIBUTES" AS ENUM (
  'height',
  'width',
  'family',
  'genus',
  'species',
  'habit',
  'common names',
  'flowering time',
  'soil types'
);

CREATE TYPE "ACTUAL_PLANT_ATTRIBUTES" AS ENUM (
  'name',
  'date_planted',
  'height',
  'width',
  'source',
  'observation'
);

CREATE TABLE "generic_plants" (
  "g_plant_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "family" varchar(20),
  "genus" varchar(20),
  "species" varchar(20),
  "height" integer,
  "width" integer
);

CREATE TABLE "gp_habits" (
  "g_plant_id" integer,
  "habit" HABIT_TYPE,
  PRIMARY KEY ("g_plant_id", "habit")
);

CREATE TABLE "gp_flowering_time" (
  "g_plant_id" integer,
  "flowering_month" MONTHS,
  PRIMARY KEY ("g_plant_id", "flowering_month")
);

CREATE TABLE "gp_common_names" (
  "g_plant_id" integer,
  "common_name" varchar(40),
  PRIMARY KEY ("g_plant_id", "common_name")
);

CREATE TABLE "gp_soil_types" (
  "g_plant_id" integer PRIMARY KEY,
  "soil_type" varchar(30)
);

CREATE TABLE "actual_plants" (
  "a_plant_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30),
  "date_planted" datetime,
  "source" varchar(50),
  "assigned_space_id" integer,
  "g_plant_id" integer
);

CREATE TABLE "spaces" (
  "space_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(60),
  "x_coodinate" real,
  "y_coordinate" real,
  "author_id" integer
);

CREATE TABLE "space_permissions" (
  "space_id" integer,
  "user_id" integer,
  "admin" boolean,
  "create" boolean,
  "update" boolean,
  "read" boolean,
  PRIMARY KEY ("space_id", "user_id")
);

CREATE TABLE "users" (
  "user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(20),
  "first_name" varchar(20),
  "last_name" varchar(20),
  "password" varchar(128)
);

CREATE TABLE "images" (
  "image_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "path" varchar(50),
  "date_uploaded" datetime,
  "uploaded_by" integer
);

CREATE TABLE "gp_images" (
  "g_plant_id" integer,
  "image_id" integer,
  PRIMARY KEY ("g_plant_id", "image_id")
);

CREATE TABLE "ap_images" (
  "a_plant_id" integer,
  "image_id" integer,
  "display_photo" boolean,
  "comment" text,
  PRIMARY KEY ("a_plant_id", "image_id")
);

CREATE TABLE "obs_images" (
  "observation_id" integer,
  "image_id" integer,
  PRIMARY KEY ("observation_id", "image_id")
);

CREATE TABLE "observations" (
  "observation_id" integer PRIMARY KEY,
  "observation_date" datetime,
  "date_authored" datetime,
  "author_id" integer,
  "a_plant_id" integer
);

CREATE TABLE "pest" (
  "observation_id" integer PRIMARY KEY,
  "name" varchar(30)
);

CREATE TABLE "pest_spread" (
  "observation_id" integer,
  "affected_location" varchar(30),
  PRIMARY KEY ("observation_id", "affected_location")
);

CREATE TABLE "disease" (
  "observation_id" integer PRIMARY KEY,
  "name" varchar(30),
  "count" integer
);

CREATE TABLE "disease_spread" (
  "observation_id" integer,
  "disease_spread" varchar(30),
  PRIMARY KEY ("observation_id", "disease_spread")
);

CREATE TABLE "comment" (
  "observation_id" integer PRIMARY KEY,
  "text" text
);

CREATE TABLE "flowering" (
  "observation_id" integer PRIMARY KEY,
  "count" integer,
  "stage" FLOWER_STAGE
);

CREATE TABLE "wildlife" (
  "observation_id" integer PRIMARY KEY,
  "name" varchar(20),
  "count" integer,
  "length_of_time" integer
);

CREATE TABLE "gp_modifications" (
  "g_plant_id" integer,
  "user_id" integer,
  "date" datetime,
  "description" text,
  PRIMARY KEY ("g_plant_id", "user_id")
);

CREATE TABLE "gp_mod_attributes" (
  "g_plant_id" integer,
  "user_id" integer,
  "modified_attribute" GENERIC_PLANT_ATTRIBUTES,
  PRIMARY KEY ("g_plant_id", "user_id", "modified_attribute")
);

CREATE TABLE "ap_modifications" (
  "a_plant_id" integer,
  "user_id" intger,
  "date" datetime,
  "description" text,
  PRIMARY KEY ("a_plant_id", "user_id")
);

CREATE TABLE "ap_mod_attributes" (
  "a_plant_id" integer,
  "user_id" integer,
  "modified_attribute" ACTUAL_PLANT_ATTRIBUTES,
  PRIMARY KEY ("a_plant_id", "user_id", "modified_attribute")
);

ALTER TABLE "gp_habits" ADD FOREIGN KEY ("g_plant_id") REFERENCES "generic_plants" ("g_plant_id");

ALTER TABLE "gp_flowering_time" ADD FOREIGN KEY ("g_plant_id") REFERENCES "generic_plants" ("g_plant_id");

ALTER TABLE "gp_common_names" ADD FOREIGN KEY ("g_plant_id") REFERENCES "generic_plants" ("g_plant_id");

ALTER TABLE "gp_soil_types" ADD FOREIGN KEY ("g_plant_id") REFERENCES "generic_plants" ("g_plant_id");

ALTER TABLE "actual_plants" ADD FOREIGN KEY ("assigned_space_id") REFERENCES "spaces" ("space_id");

ALTER TABLE "actual_plants" ADD FOREIGN KEY ("g_plant_id") REFERENCES "generic_plants" ("g_plant_id");

ALTER TABLE "spaces" ADD FOREIGN KEY ("author_id") REFERENCES "users" ("user_id");

ALTER TABLE "space_permissions" ADD FOREIGN KEY ("space_id") REFERENCES "spaces" ("space_id");

ALTER TABLE "space_permissions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "images" ADD FOREIGN KEY ("uploaded_by") REFERENCES "users" ("user_id");

ALTER TABLE "gp_images" ADD FOREIGN KEY ("g_plant_id") REFERENCES "generic_plants" ("g_plant_id");

ALTER TABLE "gp_images" ADD FOREIGN KEY ("image_id") REFERENCES "images" ("image_id");

ALTER TABLE "ap_images" ADD FOREIGN KEY ("a_plant_id") REFERENCES "actual_plants" ("a_plant_id");

ALTER TABLE "ap_images" ADD FOREIGN KEY ("image_id") REFERENCES "images" ("image_id");

ALTER TABLE "obs_images" ADD FOREIGN KEY ("observation_id") REFERENCES "observations" ("observation_id");

ALTER TABLE "obs_images" ADD FOREIGN KEY ("image_id") REFERENCES "images" ("image_id");

ALTER TABLE "observations" ADD FOREIGN KEY ("author_id") REFERENCES "users" ("user_id");

ALTER TABLE "observations" ADD FOREIGN KEY ("a_plant_id") REFERENCES "actual_plants" ("a_plant_id");

ALTER TABLE "pest" ADD FOREIGN KEY ("observation_id") REFERENCES "observations" ("observation_id");

ALTER TABLE "pest_spread" ADD FOREIGN KEY ("observation_id") REFERENCES "pest" ("observation_id");

ALTER TABLE "disease" ADD FOREIGN KEY ("observation_id") REFERENCES "observations" ("observation_id");

ALTER TABLE "disease_spread" ADD FOREIGN KEY ("observation_id") REFERENCES "disease" ("observation_id");

ALTER TABLE "comment" ADD FOREIGN KEY ("observation_id") REFERENCES "observations" ("observation_id");

ALTER TABLE "flowering" ADD FOREIGN KEY ("observation_id") REFERENCES "observations" ("observation_id");

ALTER TABLE "wildlife" ADD FOREIGN KEY ("observation_id") REFERENCES "observations" ("observation_id");

ALTER TABLE "gp_modifications" ADD FOREIGN KEY ("g_plant_id") REFERENCES "generic_plants" ("g_plant_id");

ALTER TABLE "gp_modifications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "gp_mod_attributes" ADD FOREIGN KEY ("g_plant_id") REFERENCES "gp_modifications" ("g_plant_id");

ALTER TABLE "gp_mod_attributes" ADD FOREIGN KEY ("user_id") REFERENCES "gp_modifications" ("user_id");

ALTER TABLE "ap_modifications" ADD FOREIGN KEY ("a_plant_id") REFERENCES "actual_plants" ("a_plant_id");

ALTER TABLE "ap_modifications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "ap_mod_attributes" ADD FOREIGN KEY ("a_plant_id") REFERENCES "ap_modifications" ("a_plant_id");

ALTER TABLE "ap_mod_attributes" ADD FOREIGN KEY ("user_id") REFERENCES "ap_modifications" ("user_id");
